dist: trusty
sudo: required
language: ruby
services:
  - docker
rvm:
- 2.3.1

script:
- pwd
- docker --version
- docker build -t limarka -f containers/Dockerfile-ruby-tinytex.production .
- cd modelo-oficial && docker run --mount src=`pwd`,target=/trabalho,type=bind limarka exec && cd ..
- ls -n modelo-oficial/
- file modelo-oficial/xxx-Monografia-projeto.pdf
- rm -rf modelo-oficial/xxx*
- sed -i '8 a \\\\usepackage{subfig}' modelo-oficial/latexcustomizacao.sty
- cat modelo-oficial/latexcustomizacao.sty
- echo "FROM limarka:latest" > modelo-oficial/Dockerfile && echo "RUN tlmgr install subfig" >> modelo-oficial/Dockerfile
- cat modelo-oficial/Dockerfile
- cd modelo-oficial && docker build -t limarka:custom --cache-from limarka . && cd ..
- cd modelo-oficial && docker run --mount src=`pwd`,target=/trabalho,type=bind limarka:custom exec && cd ..
- ls -n modelo-oficial/
- cat modelo-oficial/xxx-Monografia-projeto.log
- file modelo-oficial/xxx-Monografia-projeto.pdf
#after_failure:
