dist: trusty
sudo: required
language: ruby
services:
  - docker
rvm:
- 2.3.1

script:
- docker --version
- docker build -t limarka1 -f containers/Dockerfile-ruby-tinytex.production .
- cd modelo-oficial && docker run -d -it --name limarka_teste --mount src=`pwd`,target=/trabalho,type=bind limarka1  && cd ..
- docker exec limarka_teste limarka exec 
- ls -n modelo-oficial/
- file modelo-oficial/xxx-Monografia-projeto.pdf
- sed -i '8 a \\\\usepackage{subfig}' modelo-oficial/latexcustomizacao.sty
- cat modelo-oficial/latexcustomizacao.sty
- rm -rf modelo-oficial/xxx*
- docker exec limarka_teste tlmgr install subfig
- docker exec limarka_teste limarka exec
- ls -n modelo-oficial/
- cat modelo-oficial/xxx-Monografia-projeto.log
- file modelo-oficial/xxx-Monografia-projeto.pdf

#after_failure:
