dist: xenial
sudo: required
language: ruby
services:
- docker
cache: bundle
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq
  language-pack-pt
  libreoffice
  locales
  pdfgrep
  pdftk
  poppler-utils
  ruby-full
  unzip
  xclip
- wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
  && sudo dpkg -i pandoc-*.deb
- wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
- tlmgr install
  abntex2
  babel-portuges
  enumitem
  ifetex
  lastpage
  lipsum
  listings
  memoir
  microtype
  pdfpages
  textcase
  xcolor
- export PATH=$PATH:~/bin
script:
- latexmk -v
- xelatex -v
- pdftotext -v
- pandoc -v
- docker --version
- libreoffice --version
- bundle exec rspec -t @latex_minimo
- bundle exec rake
- bundle exec rake spec:latex
after_failure:
- cat test/latex/exemplo-minimo/xxx-Monografia.log
deploy:
  matrix:
  - provider: script
    skip_cleanup: true
    script: bin/build-docker.sh && bin/deploy-docker.sh $TRAVIS_TAG
  - provider: rubygems
    api_key:
      secure: YLuHbYsHGPTHoXIBr874CbIAn0/z0H0B8aW39NDQIwk7SMsd4HBgTq/6zgtUVLsp3AO9daHzk0FGcMKAOh9fxFzUuA5MmQTdQA8A3VI7JRM2BEVl8x6Hw2bjMTYMCAVGNGZT9oFKIq2lHByf9zDoQlT7CobKCY3Ofa0MTKcGgvfnqaW+VGosKrcYyZ9HPxBkH8SGnzef1joIcdtWOi3HHV28AacgRslWEkwTmYrsQcamTafQazuIbdhQ5UzvKS6PuIX56wvP6ugy9QTPtsU82x7oaDk+5e8ULJ2BMu/jwM4H3/aJ8ASg17a2EeIJRFckjQpMc+P3WCnbTu4tV2NqsXRzNmTcqwsM4bHTX2/WPlvVNwmTE9f5wSR9uCoQbDvCimCoo0miAE7xMbik0zvWVYZFtIcw3Rn+F+36jXXzY5xLSSYIZgJATbQgnNrYzCs54mUtmF+kUhYzDov4VfYcbc4ihEP6A/AdxvxuO4/xkGIsxlzxjCSw/Bs369zDXO5uUtORSQsLYPW4gZM+p++UMR63l7Radaq45HX0AVtkg9oWMj/UO8XCE2nMEUelcfeseuyy8ZB/Ga97KFVQH/LZLJYYU8+qDXQdfe8oWOlthuOA2QKyErDWQ9YWW2LVRhTacVjLBkYeChgpCReT1FDW982jfSWFCJTtb/XkM+D/90U=
    gem: limarka
    on:
      repo: abntex/limarka
