dist: bionic
sudo: required
language: ruby
services:
- docker
notifications:
  webhooks: https://coveralls.io/webhook
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: testes
      before_install:
      - sudo apt-get update -qq
      - bin/instalador.sh -dp
      before_script:
        - pandoc -v
        - git clone --depth=1 https://github.com/abntex/trabalho-academico-limarka.git modelo-oficial
      script:
      - bundle exec rake spec:ruby
      - bundle exec rake cucumber:ruby
    - stage: testes
      cache:
        directories:
          - $HOME/.TinyTeX
      before_install:
      - sudo apt-get update -qq
      - export PATH=$PATH:~/.TinyTeX/bin/x86_64-linux
      - bin/instalador.sh -dptc
      before_script:
        - latexmk -v
        - xelatex -v
        - pdftotext -v
        - pandoc -v
        - git clone --depth=1 https://github.com/abntex/trabalho-academico-limarka.git modelo-oficial
      script:
      - bundle exec rspec spec/dependencias/latex_spec.rb
      - bundle exec rspec spec/simples_spec.rb
      - bundle exec rake spec:pdf
      - bundle exec rake cucumber:pdf
      after_failure:
      - cat test/latex/exemplo-minimo/xxx-Monografia.log
      - cat tmp/simples/xxx-trabalho-academico.tex
      - cat tmp/simples/xxx-trabalho-academico.log
      - cat tmp/simples/xxx-trabalho-academico.txt
    - stage: deploy
      install: skip
      script: echo tag $TRAVIS_TAG slug $TRAVIS_REPO_SLUG branch $TRAVIS_BRANCH
      deploy:
      - provider: rubygems
        api_key:
          secure: YLuHbYsHGPTHoXIBr874CbIAn0/z0H0B8aW39NDQIwk7SMsd4HBgTq/6zgtUVLsp3AO9daHzk0FGcMKAOh9fxFzUuA5MmQTdQA8A3VI7JRM2BEVl8x6Hw2bjMTYMCAVGNGZT9oFKIq2lHByf9zDoQlT7CobKCY3Ofa0MTKcGgvfnqaW+VGosKrcYyZ9HPxBkH8SGnzef1joIcdtWOi3HHV28AacgRslWEkwTmYrsQcamTafQazuIbdhQ5UzvKS6PuIX56wvP6ugy9QTPtsU82x7oaDk+5e8ULJ2BMu/jwM4H3/aJ8ASg17a2EeIJRFckjQpMc+P3WCnbTu4tV2NqsXRzNmTcqwsM4bHTX2/WPlvVNwmTE9f5wSR9uCoQbDvCimCoo0miAE7xMbik0zvWVYZFtIcw3Rn+F+36jXXzY5xLSSYIZgJATbQgnNrYzCs54mUtmF+kUhYzDov4VfYcbc4ihEP6A/AdxvxuO4/xkGIsxlzxjCSw/Bs369zDXO5uUtORSQsLYPW4gZM+p++UMR63l7Radaq45HX0AVtkg9oWMj/UO8XCE2nMEUelcfeseuyy8ZB/Ga97KFVQH/LZLJYYU8+qDXQdfe8oWOlthuOA2QKyErDWQ9YWW2LVRhTacVjLBkYeChgpCReT1FDW982jfSWFCJTtb/XkM+D/90U=
        on:
          branch: master
      - provider: script
        script: bin/build-docker.sh && bin/deploy-docker.sh
        on:
          repo: abntex/limarka
          branch: master
      - provider: script
        script: bin/build-docker.sh && bin/deploy-docker.sh $TRAVIS_TAG
        on:
          tags: true
        after_failure:
          - cat /root/.TinyTeX/texmf-var/web2c/tlmgr.log
