dist: trusty
sudo: required
language: ruby
services:
  - docker
rvm:
- 2.3.1

script:
- docker --version
- bundle exec rake docker:build docker:run
- ls -n modelo-oficial/
- file modelo-oficial/xxx-Monografia-projeto.pdf
- sed -i '8 a \\usepackage{subfig}' modelo-oficial/latexcustomizacao.sty
- cat modelo-oficial/latexcustomizacao.sty
- rm -rf modelo-oficial/xxx*
- bundle exec rake docker:build docker:run
- ls -n modelo-oficial/
- cat modelo-oficial/xxx-Monografia-projeto.log
- file modelo-oficial/xxx-Monografia-projeto.pdf

#after_failure:
