dist: trusty
sudo: required
language: ruby
services:
  - docker
rvm:
- 2.3.1

script:
- docker --version
- bundle exec rake docker:build docker:run
- ls -n modelo-oficial/
- file modelo-oficial/xxx-Monografia-projeto.pdf
- pdftotext xxx-Monografia-projeto.pdf
- cat xxx-Monografia-projeto.txt
#after_failure: