dist: trusty
sudo: required
language: ruby
rvm:
- 2.3.1
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq ruby-full pdftk xclip poppler-utils language-pack-pt libreoffice unzip pdfgrep locales
- wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb && sudo dpkg -i pandoc-*.deb
- wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
- tlmgr install memoir abntex2 lm latex lastpage tools graphics microtype lipsum hyperref pdfpages caption
- export PATH=$PATH:~/bin

script:
- latexmk -v
- xelatex -v
- pdftotext -v
- pandoc -v
- libreoffice --version
- bundle exec rspec -t @latex_minimo
- bundle exec rake
- bundle exec rake spec:latex
#after_failure:
