dist: xenial
sudo: required
language: ruby
services:
- docker
notifications:
  webhooks: https://coveralls.io/webhook
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: testes
      before_install:
      - sudo apt-get update -qq
      - bin/instalador.sh -dp
      before_script:
        - pandoc -v
        - libreoffice --version
        - pdftk --version
      script:
      - bundle exec rake spec:ruby
    - stage: testes
      cache:
        directories:
          - $HOME/.TinyTeX
      before_install:
      - sudo apt-get update -qq
      - export PATH=$PATH:~/.TinyTeX2/bin/x86_64-linux
      - bin/instalador.sh -dptc
      before_script:
        - latexmk -v
        - xelatex -v
        - pdftotext -v
        - pandoc -v
        - libreoffice --version
        - pdftk --version
      script:
      - bundle exec rake spec:pdf
      after_failure:
      - cat tmp/anexos/ativado/xxx-Monografia-projeto.log
      - cat tmp/anexos/ativado/xxx-Monografia-projeto.log
      - cat tmp/apendices/ativado/xxx-Monografia-projeto.log
      - cat tmp/capa/capa-pdf-personalizada/xxx-Monografia-projeto.log
      - cat tmp/capa/sem-capa-personalizada/xxx-Monografia-projeto.log
      - cat tmp/errata/ativada/xxx-Monografia-projeto.log
      - cat tmp/errata/desativada/xxx-Monografia-projeto.log
      - cat tmp/exemplos/exemplo2/xxx-Monografia-projeto.log
      - cat tmp/folha_aprovacao/desativada/xxx-Monografia-projeto.log
      - cat tmp/folha_aprovacao/geracao-proposito-personalizado/xxx-Monografia-projeto.log
      - cat tmp/folha_aprovacao/geracao/xxx-Monografia-projeto.log
      - cat tmp/folha_aprovacao/inclusao/xxx-Monografia-projeto.log
      - cat tmp/latex/exemplo-minimo-com-acentos/xxx-Monografia.log
      - cat tmp/latex/exemplo-minimo/xxx-Monografia.log
      - cat tmp/latex/exemplo-pequeno-latex/xxx-Monografia.log
      - cat tmp/lista_ilustracoes/ativada/xxx-Monografia-projeto.log
      - cat tmp/lista_tabelas/ativada/xxx-Monografia-projeto.log
      - cat tmp/lista_tabelas/desativada/xxx-Monografia-projeto.log
      - cat tmp/preambulo/projeto/xxx-Monografia-projeto.log
      - cat tmp/preambulo/trabalho-final/xxx-Monografia.log
      - cat tmp/referencias_bib/xxx-Monografia-projeto.log
      - cat tmp/siglas/especificadas/xxx-Monografia-projeto.log
      - cat tmp/siglas/padrao/xxx-Monografia-projeto.log
      - cat tmp/simbolos/especificados/xxx-Monografia-projeto.log
      - cat tmp/sumario/sem-siglas/xxx-Monografia-projeto.log
      - cat tmp/sumario/siglas-nil/xxx-Monografia-projeto.log
    - stage: deploy
      install: skip
      script: echo tag $TRAVIS_TAG slug $TRAVIS_REPO_SLUG branch $TRAVIS_BRANCH
      deploy:
      - provider: rubygems
        api_key:
          secure: YLuHbYsHGPTHoXIBr874CbIAn0/z0H0B8aW39NDQIwk7SMsd4HBgTq/6zgtUVLsp3AO9daHzk0FGcMKAOh9fxFzUuA5MmQTdQA8A3VI7JRM2BEVl8x6Hw2bjMTYMCAVGNGZT9oFKIq2lHByf9zDoQlT7CobKCY3Ofa0MTKcGgvfnqaW+VGosKrcYyZ9HPxBkH8SGnzef1joIcdtWOi3HHV28AacgRslWEkwTmYrsQcamTafQazuIbdhQ5UzvKS6PuIX56wvP6ugy9QTPtsU82x7oaDk+5e8ULJ2BMu/jwM4H3/aJ8ASg17a2EeIJRFckjQpMc+P3WCnbTu4tV2NqsXRzNmTcqwsM4bHTX2/WPlvVNwmTE9f5wSR9uCoQbDvCimCoo0miAE7xMbik0zvWVYZFtIcw3Rn+F+36jXXzY5xLSSYIZgJATbQgnNrYzCs54mUtmF+kUhYzDov4VfYcbc4ihEP6A/AdxvxuO4/xkGIsxlzxjCSw/Bs369zDXO5uUtORSQsLYPW4gZM+p++UMR63l7Radaq45HX0AVtkg9oWMj/UO8XCE2nMEUelcfeseuyy8ZB/Ga97KFVQH/LZLJYYU8+qDXQdfe8oWOlthuOA2QKyErDWQ9YWW2LVRhTacVjLBkYeChgpCReT1FDW982jfSWFCJTtb/XkM+D/90U=
        on:
          branches:
            only:
              - master
      - provider: rubygems
        api_key:
          secure: YLuHbYsHGPTHoXIBr874CbIAn0/z0H0B8aW39NDQIwk7SMsd4HBgTq/6zgtUVLsp3AO9daHzk0FGcMKAOh9fxFzUuA5MmQTdQA8A3VI7JRM2BEVl8x6Hw2bjMTYMCAVGNGZT9oFKIq2lHByf9zDoQlT7CobKCY3Ofa0MTKcGgvfnqaW+VGosKrcYyZ9HPxBkH8SGnzef1joIcdtWOi3HHV28AacgRslWEkwTmYrsQcamTafQazuIbdhQ5UzvKS6PuIX56wvP6ugy9QTPtsU82x7oaDk+5e8ULJ2BMu/jwM4H3/aJ8ASg17a2EeIJRFckjQpMc+P3WCnbTu4tV2NqsXRzNmTcqwsM4bHTX2/WPlvVNwmTE9f5wSR9uCoQbDvCimCoo0miAE7xMbik0zvWVYZFtIcw3Rn+F+36jXXzY5xLSSYIZgJATbQgnNrYzCs54mUtmF+kUhYzDov4VfYcbc4ihEP6A/AdxvxuO4/xkGIsxlzxjCSw/Bs369zDXO5uUtORSQsLYPW4gZM+p++UMR63l7Radaq45HX0AVtkg9oWMj/UO8XCE2nMEUelcfeseuyy8ZB/Ga97KFVQH/LZLJYYU8+qDXQdfe8oWOlthuOA2QKyErDWQ9YWW2LVRhTacVjLBkYeChgpCReT1FDW982jfSWFCJTtb/XkM+D/90U=
        on:
          tag: true
          all_branches: true
      - provider: script
        script: bin/build-docker.sh && bin/deploy-docker.sh
        on:
          repo: abntex/limarka
          branches:
            only:
              - master
      - provider: script
        script: bin/build-docker.sh && bin/deploy-docker.sh $TRAVIS_TAG
        on:
          tags: true
