dist: trusty
sudo: required
language: ruby
services:
- docker
rvm:
- 2.3.1

before_install:
- sudo apt-get update -qq && sudo apt-get install -y -qq \
    language-pack-pt\
    libreoffice \
    locales \
    pdfgrep \
    poppler-utils \
    pdftk xclip \
    ruby-full \
    unzip
- wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb && sudo dpkg -i pandoc-*.deb
- wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
- tlmgr install memoir abntex2 lastpage microtype lipsum pdfpages ifetex textcase enumitem xcolor babel-portuges listings
- export PATH=$PATH:~/bin

script:
- latexmk -v
- xelatex -v
- pdftotext -v
- pandoc -v
- docker --version
- libreoffice --version
- bundle exec rspec -t @latex_minimo
- bundle exec rake
- bundle exec rake spec:latex
- bundle exec rake docker:build

after_failure:
  - cat test/latex/exemplo-minimo/xxx-Monografia.log

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/build-docker.sh && bin/deploy-docker.sh tag $TRAVIS_TAG
    on:
      tag: true
  - provider: script
    skip_cleanup: true
    script: bin/build-docker.sh && bin/deploy-docker.sh branch dev
    on:
      branch: master
      tags: false
