dist: trusty
sudo: required
language: ruby
services:
  - docker
rvm:
- 2.3.1

script:
- docker --version
- bundle exec rake docker:build docker:run
after_failure:
  - cat /usr/local/bundle/extensions/x86_64-linux/2.6.0/ffi-1.10.0/mkmf.log
  - ls -n modelo-oficial/xxx*
