dist: trusty
sudo: required
language: ruby
services:
- docker
rvm:
- 2.3.1
cache: bundle

script:
- docker --version

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/build-docker.sh && bin/deploy-docker.sh tag $TRAVIS_TAG
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bin/build-docker.sh && bin/deploy-docker.sh branch dev
    on:
      branch: master
      tags: false
