---
instituicao: Universidade/Faculdade do Brasil
author: Nome do autor
title: Título do trabalho
local: Cidade - UF
date: '2016'
linha_de_pesquisa: ''
area_de_concentracao: Computação
titulacao: Minha-titulação
curso: Meu-curso
coorientador: ''
programa: Programa de Pós-Graduação em XXX
orientador: Nome-do-Orientador
referencias_caminho: referencias.bib
proposito: ''
palavras_chave: ''
resumo: ''
keywords: ''
abstract_texto: ''
resumen: ''
palabras_clave: ''
mots_cles: ''
resume: ''
siglas:
- s: ABNT
  d: Associação Brasileira de Normas Técnicas
simbolos: 
dedicatoria: ''
agradecimentos: ''
epigrafe: ''
avaliador1: Nome-do-Prof-Convidado1
aprovacao_dia: '1'
avaliador2: Nome-do-Prof-Convidado2
avaliador3: ''
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Monografia
incluir_ficha_catalografica: false
folha_de_aprovacao: false
projeto: true
apendices: false
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: false
lista_tabelas: false

---
